### ISSUE TITLE
A safe navigation operator

### ISSUE THREAD

**Issue by majioa** [rubinius/rubinius-code#8]
## Problem

The exception is thrown in the code:

> SyntaxError: syntax error, unexpected '.': /home/travis/build/znamenica/bukovina/lib/bukovina/parsers/name.rb:51:42
## How to Reproduce

The problem is risen up because of new operator of ruby (mri) 2.3.0 isn't exist in  rubinius:

> [A safe navigation operator (so-called lonely operator) &., which already exists in C#, Groovy, and Swift, is introduced to ease nil handling as obj&.foo. Array#dig and Hash#dig are also added. Note that this behaves like try! of Active Support, which specially handles only nil.](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/)

The problem present in both 2.11 and 3.19 versions.

Related from: https://github.com/rubinius/rubinius/issues/3629

**Comment by brixen** [comment]
This is fixed https://github.com/rubinius/rubinius/issues/3629
